
import java.util.Scanner;

public class CheckOutSystem{





	public static void main (String [] args){

Scanner input = new scanner(system.in);

System.out.println("Enter items name");
System.out.println("Enter price");
System.out.println("Eter quantity")

Strings itemsNames = obtained.nextline();

double price= obtained.nextDouble();

int productquantity = obtained.nextInt();

doubletotal =quantity*price

double total = productprice* productQuantity
double discount =2/100 * total
double vat = 7.5/100* total

system.out.printf(

"product name:%s";
"price:2f";
"Quantity:%d";
"Total:2f";
"Discount:2f";
"vat@7.5%%:";
"=================";
"sumTotal:%.2f"

product

""");




)
		
